### PR TITLE
add support for comma separator between elements - fixes #17

### LINKED ISSUE #17: Support commas between elements
See https://github.com/hjson/hjson-js/issues/16#issue-195740798.

The output of the stringify call returns key-value pairs without commas. So this is what I get

```json
{
    foo: "bar"
    unicorn: "rainbow"
}
```

This is probably intended. I think it would be nice if there was an option to at least allow commas between elements.

```json
{
    foo: "bar",
    unicorn: "rainbow"
}
```

### PR DESCRIPTION
**Pull request by SamVerschueren**
Feel free to provide feedback of any kind. Things you want differently (code style, documentation wording, option name).

I wanted to add tests for this as well but I couldn't get a grip on how these work in this project :).

### CODE REVIEW

**Comment by laktak** [comment]
Thanks, your code looks good but there is a conflict with Hjson's unquoted strings.

For `{ "a": "text", "b": "text" }` this would produce

```
{
  a: text,
  b: text
}
```

Since unquoted strings end at the LF you can't really place a comma on that line. Omitting them for unquoted strings would make no sense so we should restrict this option to quoted strings.

Because it is easier to explain, just enable quoted strings if commas are enabled.

Tests can be added in `test/assets/extra`, see the mltab sample. The separator option can then be enabled in *meta.hjson with
```
{
  options: {
    separator: true
  }
}
```

Since hjson still supports node 0.x please use var instead of const (see Travis).

**Comment by SamVerschueren** [comment]
Added tests, fixed the `const` and made quotes `always` when `separator` is set to `true`. 

If you want to test another scenario, feel free to suggest improvements!

**Comment by laktak** [comment]
Looks good! I added a stringify(with separators)->parse step for all test cases and they ran without issues.

Thanks for also adding the option to the api doc.

Could you remove the trailing whitespace (in test/assets/extra/separator_testmeta.hjson) before I merge?

**Comment by SamVerschueren** [comment]
Awesome! Fixed the whitespace.

> Could you remove the trailing whitespace (in test/assets/extra/separator_testmeta.hjson) before I merge?

Might be a good idea to add a [EditorConfig](http://editorconfig.org) file. An example could be found [here](https://github.com/SamVerschueren/listr-update-renderer/blob/master/.editorconfig) and in any of my (and many many others as well) repositories. This way it's easier do file PRs because you as maintainer can easily force indentation (tabs/spaces), trim trailing whitespace etc. It's just a suggestion though :).

**Comment by laktak** [comment]
Thank you!

Haven't heard of EditorConfig before. Looks interesting but how do you enforce it? Is there a package I can add to the lint step?

**Comment by SamVerschueren** [comment]
Thanks for mergin! I will have a look at #16 as well.

> Haven't heard of EditorConfig before. Looks interesting but how do you enforce it? Is there a package I can add to the lint step?

It's not something like a lint step. If you want to lint trailing whitespaces and tabs/spaces, I'd suggest adding [ESLint](http://eslint.org/) or [XO](https://github.com/sindresorhus/xo) (which I prefer because it's very easy to set up). They are perfectly capable of enforcing that in a lint step.

[EditorConfig](http://editorconfig.org/) however is, like the name implies, a config for editors. You need a plugin for the editor you use, but if you scroll down on the website, you'll notice that all the common editors have it.
You as maintainer add the `.editorconfig` file to your repository and decide which settings (tabs, spaces, indentation, trailing whitespace, ...) you want for your files. If I as a contributor create a PR, my editor picks up the configuration and I don't have to worry about the settings because you decided everything. This is perfect if you work in teams where you don't want to end up with one file being tabs, other files being spaces because everyone has different editor settings.

Hope my explanation is a bit clear :).

**Comment by laktak** [comment]
I'm not sure about EditorConfig but I've added one if it helps. Could you take a look if the file is OK?

And thanks for the ESLint tip! I replaced the old linter and added everything to the build step & travis.

**Comment by laktak** [comment]
@SamVerschueren the new version is now published to npm

**Pull request merged**
