### PR TITLE
add support for quotes around keys - fixes #16

### LINKED ISSUE #16: Support quotes around keys
Hi, I really like this library as it allows me to add comments to my JSON files. That is the only feature I want (for now) as I like to use this as config parser for [alfy](https://github.com/sindresorhus/alfy).

What I noticed however, is that it does two things that keeps me from using this library.

#### No trailing commas
The output of the `stringify` call returns key-value pairs without commas. So this is what I get
```json
{
    foo: "bar"
    unicorn: "rainbow"
}
```

This is probably intended. I think it would be nice if there was an option to at least allow trailing commas to be added.

#### Quotes around keys
By default, it doesn't quote anything, not even string values. So I used the `quotes` option and set it to `always`. This adds quotes around string values, but not around keys. It might make sense if there was an extra option like `min`, `values`, `always` or something. Where `always` also wraps the keys.

// @sindresorhus

### PR DESCRIPTION
**Pull request by SamVerschueren**
This PR adds support for #16 by extending the `quotes` option. It now accepts the following values.

- `min`: no quotes whenever possible (default)
- `keys`: use quotes around keys
- `strings`: use quotes around string values
- `all`: use quotes around keys and string values

The `always` value still works and is treated as `strings` to keep compatibility with what we had before. I also didn't touch the CLI. I can still do that if you want. I would suggest using `-quote=strings` or something. Let me know if you want me to add it in this PR.

I also added a 3rd option to `multiline`, the option `off`.

Let me know if you want some things to be changed, added, removed, ...

### CODE REVIEW

**Comment by laktak** [comment]
Thanks, looks great!

I'll move that one check back because the tests are used for all Hjson implementations and the others only support one directory at the moment.

**Comment by SamVerschueren** [comment]
Hi @laktak, you're welcome! Let me know when you've released a new version.

> I'll move that one check back because the tests are used for all Hjson implementations and the others only support one directory at the moment.

Sure, no problem.

**Comment by laktak** [comment]
@SamVerschueren the new version is now published to npm

**Comment by SamVerschueren** [comment]
Thank you very much @laktak! Works perfectly (https://github.com/SamVerschueren/human-config-merge)!

**Pull request merged**
